# Puerto
server.port=8080

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HospitalDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sql

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# JWT
app.jwt.secret=cambia-esta-clave-por-una-de-al-menos-32-caracteres-super-secreta-2026
app.jwt.expiration-ms=28800000

# Configuracion Gemini Chatbot
gemini.api.key=AQ.Ab8RN6K47u8RNtreuh-Y4ITVK92G954_dgWyhO94bXJt1n4ZYQ
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent